### PR TITLE
Bolder map marker. Alerts if song is added to playlist. Beatdrops log…

### PR DESCRIPTION
**Pull request by naomidonato**
…o on homepage. 

Bolder map marker. Alerts if song is added to playlist. Beatdrops logo on homepage.
Map is scaled to be bigger.

### CODE REVIEW

**Comment by matthewhung09** [comment]
No comments, looks good to me!

**Review by matthewhung09 — COMMENTED** [review]
No comments, looks good to me!

**Review by gscotti6950 — COMMENTED** [review]
Looks good. Great job!

**Comment by adellevo** [comment]
No comments, great job!

**Review by adellevo — COMMENTED** [review]
No comments, great job!

**Pull request merged**
